name: Test GitHub Secrets Configuration

# Run this workflow manually to test your secrets
on:
  workflow_dispatch:  # Allows manual trigger
  
jobs:
  test-secrets:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test Configuration Loading
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        B2_APPLICATION_KEY_ID: ${{ secrets.B2_APPLICATION_KEY_ID }}
        B2_APPLICATION_KEY: ${{ secrets.B2_APPLICATION_KEY }}
        B2_BUCKET_NAME: ${{ secrets.B2_BUCKET_NAME }}
        B2_ENDPOINT_URL: ${{ secrets.B2_ENDPOINT_URL }}
        REDIS_URL: redis://localhost:6379/0
        ENVIRONMENT: production
      run: |
        echo "🔍 Testing GitHub Secrets Configuration..."
        
        # Test config loading
        python -c "
        from config import config
        import sys
        
        print('📋 Configuration Summary:')
        summary = config.get_config_summary()
        for key, value in summary.items():
            print(f'  {key}: {value}')
        
        print('\n🔍 Validation Results:')
        is_valid, missing = config.validate()
        if is_valid:
            print('✅ All required configuration present!')
            print('🎉 GitHub Secrets are configured correctly!')
        else:
            print(f'❌ Missing configuration: {missing}')
            print('💡 Check your GitHub Repository Secrets')
            sys.exit(1)
        "
    
    - name: Test Database Connection
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        B2_APPLICATION_KEY_ID: ${{ secrets.B2_APPLICATION_KEY_ID }}
        B2_APPLICATION_KEY: ${{ secrets.B2_APPLICATION_KEY }}
        B2_BUCKET_NAME: ${{ secrets.B2_BUCKET_NAME }}
        B2_ENDPOINT_URL: ${{ secrets.B2_ENDPOINT_URL }}
        REDIS_URL: redis://localhost:6379/0
        ENVIRONMENT: production
      run: |
        echo "🗄️ Testing Supabase Database Connection..."
        python -c "
        from database import db
        print('✅ Database client initialized successfully!')
        print('🔗 Supabase connection configured correctly!')
        "
    
    - name: Test Backblaze B2 Configuration
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        B2_APPLICATION_KEY_ID: ${{ secrets.B2_APPLICATION_KEY_ID }}
        B2_APPLICATION_KEY: ${{ secrets.B2_APPLICATION_KEY }}
        B2_BUCKET_NAME: ${{ secrets.B2_BUCKET_NAME }}
        B2_ENDPOINT_URL: ${{ secrets.B2_ENDPOINT_URL }}
        REDIS_URL: redis://localhost:6379/0
        ENVIRONMENT: production
      run: |
        echo "☁️ Testing Backblaze B2 Configuration..."
        python -c "
        from storage import storage
        print('✅ Backblaze B2 client initialized successfully!')
        print('🗂️ B2 storage configuration correct!')
        "
    
    - name: Test YouTube Parser
      run: |
        echo "🎬 Testing YouTube Parser..."
        python -c "
        from youtube_parser import YouTubeURLParser
        
        # Test URL validation
        test_url = 'https://www.youtube.com/watch?v=dQw4w9WgXcQ'
        is_valid = YouTubeURLParser.validate_url(test_url)
        
        if is_valid:
            print('✅ YouTube parser working correctly!')
        else:
            print('❌ YouTube parser test failed')
            exit(1)
        "
    
    - name: Final Summary
      run: |
        echo ""
        echo "🎉 SUCCESS! All GitHub Secrets are configured correctly!"
        echo ""
        echo "✅ Configuration loaded successfully"
        echo "✅ Supabase connection ready"
        echo "✅ Backblaze B2 storage ready"
        echo "✅ YouTube parser working"
        echo ""
        echo "🚀 Your application is ready to deploy!"